# -*- coding: utf-8 -*-
"""Copy of main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IXqaSyTvojvRgIpunBDzWZr28Q1mH1-B
"""

import sys, os
sys.path.append(os.path.abspath("./drive/MyDrive/FYP"))

import os
os.listdir("./drive/MyDrive/FYP")

sys.path

import torch
import torch.nn as nn
import math
from transformers.models.llama.modeling_llama import (
    apply_rotary_pos_emb,
    repeat_kv
)


class QuantLinear(nn.Module):
    def __init__(self, linear: nn.Linear, n_bits=8):
        super().__init__()
        self.weight = linear.weight
        self.bias = linear.bias
        self.n_bits = n_bits

    def fake_quant(self, x):
        qmin, qmax = 0, 2**self.n_bits - 1
        scale = (x.max() - x.min()) / (qmax - qmin + 1e-5)
        zero_point = -x.min() / (scale + 1e-5)
        x_int = torch.clamp((x / scale + zero_point).round(), qmin, qmax)
        return (x_int - zero_point) * scale

    def forward(self, x):
        out = x @ self.weight.T
        if self.bias is not None:
            out += self.bias
        return self.fake_quant(out)

class QuantMatMul(nn.Module):
    def __init__(self, n_bits=8):
        super().__init__()
        self.n_bits = n_bits

    def fake_quant(self, x):
        qmin, qmax = 0, 2**self.n_bits - 1
        scale = (x.max() - x.min()) / (qmax - qmin + 1e-5)
        zero_point = -x.min() / (scale + 1e-5)
        x_int = torch.clamp((x / scale + zero_point).round(), qmin, qmax)
        return (x_int - zero_point) * scale

    def forward(self, a, b):
        a = self.fake_quant(a)
        b = self.fake_quant(b)
        return torch.matmul(a, b)

debug = {}

# After Q projection
debug["q_fp"] = q_fp.detach().cpu()
debug["q_q"]  = q_q.detach().cpu()

# After attention scores
debug["attn_fp"] = attn_fp.detach().cpu()
debug["attn_q"]  = attn_q.detach().cpu()

# Final output
debug["out_fp"] = out_fp.detach().cpu()
debug["out_q"]  = out_q.detach().cpu()

class QuantLlamaAttention(nn.Module):
    def __init__(self, fp_attn):
        super().__init__()
        self.debug = {}
        self.hidden_size = fp_attn.config.hidden_size
        self.num_heads = fp_attn.config.num_attention_heads
        self.head_dim = self.hidden_size // self.num_heads
        self.num_kv_heads = fp_attn.config.num_key_value_heads
        self.num_groups = self.num_heads // self.num_kv_heads

        self.rotary_emb = fp_attn.rotary_fn

        # Quantized projections
        self.q_proj = QuantLinear(fp_attn.q_proj)
        self.k_proj = QuantLinear(fp_attn.k_proj)
        self.v_proj = QuantLinear(fp_attn.v_proj)
        self.o_proj = QuantLinear(fp_attn.o_proj)

        self.qk_matmul = QuantMatMul()
        self.pv_matmul = QuantMatMul()

    def forward(self, hidden_states, attention_mask=None, position_embeddings=None):
        B, T, C = hidden_states.shape

        # QKV
        q = self.q_proj(hidden_states)
        k = self.k_proj(hidden_states)
        v = self.v_proj(hidden_states)
        self.debug["q_q"] = q.detach().cpu()
        # reshape → heads
        q = q.view(B, T, self.num_heads, self.head_dim).transpose(1, 2)
        k = k.view(B, T, self.num_kv_heads, self.head_dim).transpose(1, 2)
        v = v.view(B, T, self.num_kv_heads, self.head_dim).transpose(1, 2)

        # rotary
        cos, sin = position_embeddings
        q, k = apply_rotary_pos_emb(q, k, cos, sin)

        # repeat kv
        k = repeat_kv(k, self.num_groups)
        v = repeat_kv(v, self.num_groups)

        # attention
        attn = self.qk_matmul(q, k.transpose(-2, -1))
        attn = attn / math.sqrt(self.head_dim)
        self.debug["attn_q"] = attn.detach().cpu()
        if attention_mask is not None:
            attn = attn + attention_mask

        attn = torch.softmax(attn, dim=-1)

        out = self.pv_matmul(attn, v)
        self.debug["out_q"] = out.detach().cpu()
        out = out.transpose(1, 2).contiguous().view(B, T, C)

        return self.o_proj(out)

"""###Testing only one attention layer for the above process"""

from transformers import AutoModelForCausalLM, AutoTokenizer

model = AutoModelForCausalLM.from_pretrained(
    "meta-llama/Llama-2-7b-hf",
    torch_dtype=torch.float16,
    device_map="auto"
)

layer = model.model.layers[0]

fp_attn = layer.self_attn
dir(fp_attn)

for name, module in layer.named_modules():
  print(module)

import inspect
print(inspect.signature(fp_attn.rotary_fn))

q_attn = QuantLlamaAttention(fp_attn).to(next(model.parameters()).device)

tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-2-7b-hf")

inputs = tokenizer("Quantization is interesting", return_tensors="pt")
inputs = inputs.to(next(model.parameters()).device)

with torch.no_grad():
    hidden = model.model.embed_tokens(inputs.input_ids)
    B, T, C = hidden.shape
    position_ids = torch.arange(T, device=hidden.device).unsqueeze(0)
    cos,sin=model.model.rotary_emb(hidden,position_ids)

    out_fp, _ = fp_attn(
        hidden_states=hidden,
        position_embeddings=(cos, sin),
        attention_mask=None,
    )
    out_q = q_attn(hidden, attention_mask=None, position_embeddings=(cos,sin),)
debug = {}
debug["out_fp"] = out_fp.detach().cpu()

# Collect Quant tensors
debug.update(q_attn.debug)

print("FP output:", out_fp[0, 0, :5])
print("Q  output:", out_q[0, 0, :5])
print(type(q_attn.q_proj))
print(type(q_attn.qk_matmul))
diff = (out_fp - out_q).abs()
print("Mean error:", diff.mean().item())
print("Max error :", diff.max().item())

dict(model.model.named_parameters())

def layer_memory_mb(layer):
    total_bytes = 0
    for p in layer.parameters():
        total_bytes += p.numel() * p.element_size()
    return total_bytes / (1024 ** 2)

fp_layer = model.model.layers[0].self_attn







